---
- name: Generate unique run id
  ansible.builtin.set_fact:
    run_id: "{{ 10000 | random | checksum }}"

- name: Create OVHcloud consumer key
  holyhope.ovh.new_consumer_key:
    accesses: "{{ accesses }}"
    endpoint: "{{ endpoint }}"
    application_key: "{{ application_key }}"
    application_secret: "{{ application_secret }}"
    redirect_url: "http://{{ waiting_address | mandatory }}:{{ waiting_port | mandatory }}/{{ run_id }}"
  register: result_ck

- name: "Please validate OVHcloud consumer key: {{ result_ck.validation_url }}"
  holyhope.ovh.wait_for_request:
    port: "{{ waiting_port }}"
    address: "{{ waiting_address }}"
    response_body: "{{ lookup('template', 'response.html.j2') }}"
  register: request
  failed_when: "run_id not in request.path"

- name: Check OVHcloud consumer key
  holyhope.ovh.consumer_key:
    endpoint: "{{ endpoint }}"
    application_key: "{{ application_key }}"
    application_secret: "{{ application_secret }}"
    consumer_key: "{{ result_ck.consumer_key }}"
  register: check_ck
  failed_when: "check_ck.failed or check_ck.state != 'validated'"

- name: Update allowed ips
  holyhope.ovh.allowed_ips:
    ips: "{{ ips }}"
    endpoint: "{{ endpoint }}"
    application_key: "{{ ansible_application_key }}"
    application_secret: "{{ ansible_application_secret }}"
    consumer_key: "{{ ansible_consumer_key }}"
    subject_credentials_id: "{{ check_ck.credential_id }}"
  when: ips

- name: Save consumer key to Ansible facts
  ansible.builtin.set_fact:
    consumer_key: "{{ result_ck.consumer_key }}"
...
