---
- name: Create OVHcloud consumer key
  holyhope.ovh.new_consumer_key:
    accesses: "{{ accesses }}"
    endpoint: "{{ endpoint }}"
    application_key: "{{ application_key }}"
    application_secret: "{{ application_secret }}"
    redirect_url: "http://{{ waiting_address | mandatory }}:{{ waiting_port | mandatory }}/{{ ansible_play_name }}"
  register: result_ck

- name: Save consumer key to Ansible facts
  ansible.builtin.set_fact:
    consumer_key: "{{ result_ck.consumer_key }}"
  no_log: True

- name: "Please validate OVHcloud consumer key: {{ result_ck.validation_url }}"
  holyhope.ovh.wait_for_request:
    port: "{{ waiting_port }}"
    address: "{{ waiting_address }}"
    response_body: "{{ lookup('template', 'response.html.j2') }}"

- name: Check OVHcloud consumer key
  holyhope.ovh.consumer_key:
    endpoint: "{{ endpoint }}"
    application_key: "{{ application_key }}"
    application_secret: "{{ application_secret }}"
    consumer_key: "{{ consumer_key }}"
  register: result_ck
  failed_when: result_ck.state != 'validated'

- name: Update allowed ips
  holyhope.ovh.allowed_ips:
    ips: "{{ ips }}"
    endpoint: "{{ endpoint }}"
    application_key: "{{ ansible_application_key }}"
    application_secret: "{{ ansible_application_secret }}"
    consumer_key: "{{ ansible_consumer_key }}"
    subject_credentials_id: "{{ result_ck.credential_id }}"
  when: ips

- name: OVHcloud Consumer key is now valid
  ansible.builtin.debug:
    var: consumer_key
...
